org.gradle.jvmargs=-Xmx6g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g
kotlin.code.style=official
android.useAndroidX=true
android.debug.obsoleteApi=true
android.nonTransitiveRClass=true

XCLICKER_STORE_FILE=xclicker.jks
XCLICKER_STORE_PASSWORD=123456
XCLICKER_KEY_ALIAS=key0
XCLICKER_KEY_PASSWORD=123456

